Repository roboblazers7617/2025Robot, pull requests merged in 2025-02, with the labels that each got.

#54 Change drivetrain log level depending on DEBUG_MODE
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
Labels: drivetrain, logging

#39 Fix rotation when starting Teleop on Red alliance
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/Dashboard.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
Labels: drivetrain

#55 Add drive to scoring position
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/Dashboard.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
  src/main/java/frc/robot/util/PoseUtil.java
  src/main/java/frc/robot/util/Util.java
Labels: drivetrain, controls

#67 Create Command factories in Drivetrain for the controller commands
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/drivetrain/Drivetrain.java
Labels: drivetrain

#63 Fix snapback after pathfinding and after returning to heading control on Red
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/drivetrain/Drivetrain.java
Labels: drivetrain, tested

#70 Add Driverstation dashboard
  src/main/deploy/elastic-layout.json
Labels: dashboard, tested

#82 Fix rotation after pathfinding to poses
  src/main/java/frc/robot/subsystems/drivetrain/Drivetrain.java
Labels: drivetrain, needs testing

#84 Tune swerve and pathplanner control loops
  src/main/deploy/pathplanner/settings.json
  src/main/deploy/swerve/modules/pidfproperties.json
  src/main/java/frc/robot/Constants.java
Labels: drivetrain, auto, tested

#89 Block untested pull requests
  .github/workflows/block-untested-prs.yml
Labels: ci

#90 Log PDH values
  src/main/java/frc/robot/Robot.java
Labels: logging, tested

#83 Bring Robot class up to coding standards
  src/main/java/frc/robot/Robot.java
Labels: tested

#81 Log DriverStation data
  src/main/java/frc/robot/Robot.java
Labels: logging, tested

#75 Add scoring positions for Algae
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/util/PoseUtil.java
Labels: drivetrain, tested

#64 Bind the LockWheelsCommand to a controller button
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/drivetrain/Drivetrain.java
Labels: drivetrain, controls, tested

#92 Reset the last angle scalar after running Auto
  src/main/java/frc/robot/RobotContainer.java
Labels: drivetrain, auto, tested

#91 Add a zeroGyroCommand to Drivetrain
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/drivetrain/Drivetrain.java
Labels: drivetrain, tested

#93 Add a center Red pose to the dashboard
  src/main/java/frc/robot/subsystems/Dashboard.java
Labels: dashboard, tested

#94 Comment out the PDH logging
  src/main/java/frc/robot/Robot.java
Labels: logging, tested

#117 Revert "Block untested pull requests"
  .github/workflows/block-untested-prs.yml
Labels: ci

#121 Change Elastic tabs automatically
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/util/Elastic.java
Labels: dashboard, tested

#87 Update WPILib to 2025.3.1
  build.gradle
  src/main/java/frc/robot/Constants.java
Labels: tested

#142 Fix robot crashing when starting an auto without selecting an alliance
  src/main/java/frc/robot/RobotContainer.java
Labels: dashboard, auto, tested

#122 Make the dashboard not a subsystem
  src/main/java/frc/robot/Dashboard.java
  src/main/java/frc/robot/RobotContainer.java
Labels: dashboard, tested

#95 Use a custom library for vision
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/drivetrain/Drivetrain.java
  src/main/java/frc/robot/subsystems/vision/LimelightHelpers.java
  src/main/java/frc/robot/subsystems/vision/Vision.java
  src/main/java/io/github/roboblazers7617/limelight/JsonUtilities.java
  src/main/java/io/github/roboblazers7617/limelight/Limelight.java
  src/main/java/io/github/roboblazers7617/limelight/LimelightSettings.java
  src/main/java/io/github/roboblazers7617/limelight/PipelineDataCollator.java
  src/main/java/io/github/roboblazers7617/limelight/PipelineResult.java
  src/main/java/io/github/roboblazers7617/limelight/PoseEstimate.java
  src/main/java/io/github/roboblazers7617/limelight/PoseEstimator.java
  src/main/java/io/github/roboblazers7617/limelight/targets/BarcodeTarget.java
  src/main/java/io/github/roboblazers7617/limelight/targets/FiducialTarget.java
  src/main/java/io/github/roboblazers7617/limelight/targets/RawFiducialTarget.java
  src/main/java/io/github/roboblazers7617/limelight/targets/RetroreflectiveTarget.java
  src/main/java/io/github/roboblazers7617/limelight/targets/neural/ClassifierTarget.java
  src/main/java/io/github/roboblazers7617/limelight/targets/neural/DetectorTarget.java
  src/main/java/io/github/roboblazers7617/limelight/targets/neural/RawDetection.java
Labels: vision

#120 Clean up setLastAngleScalar methods
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/drivetrain/Drivetrain.java
Labels: drivetrain, needs testing

#88 Add package-info files
  src/main/java/frc/robot/commands/drivetrain/package-info.java
  src/main/java/frc/robot/commands/package-info.java
  src/main/java/frc/robot/loggers/package-info.java
  src/main/java/frc/robot/package-info.java
  src/main/java/frc/robot/subsystems/drivetrain/package-info.java
  src/main/java/frc/robot/subsystems/package-info.java
  src/main/java/frc/robot/util/package-info.java
Labels: documentation

#68 Update YAGSL to 2025.3.0
  src/main/deploy/swerve/modules/physicalproperties.json
  vendordeps/PathplannerLib-2025.2.4.json
  vendordeps/Phoenix6-25.3.1.json
  vendordeps/Studica-2025.0.1.json
  vendordeps/maple-sim.json
  vendordeps/yagsl-2025.7.0.json
Labels: drivetrain, tested

#66 Add more loggers for REVLib classes
  src/main/java/frc/robot/loggers/SparkMaxLogger.java
  src/main/java/frc/robot/loggers/revlib/AbsoluteEncoderLogger.java
  src/main/java/frc/robot/loggers/revlib/RelativeEncoderLogger.java
  src/main/java/frc/robot/loggers/revlib/SparkBaseLogger.java
  src/main/java/frc/robot/loggers/revlib/SparkLimitSwitchLogger.java
  src/main/java/frc/robot/loggers/revlib/structs/SparkFaultsStruct.java
  src/main/java/frc/robot/loggers/revlib/structs/SparkWarningsStruct.java
Labels: logging, needs testing
